version: 2

defaults: &defaults
  working_directory: ~/repo
  resource_class: small

install_lint_test: &install_lint_test
  steps:
    - checkout
    - restore_cache:
        keys:
          - node-{{ .Environment.NODE_VERSION }}-cache-{{ checksum "./yarn.lock" }}
    - run: yarn install
    - run: yarn lint
    - run: yarn type-check
    - run: yarn test
    - save_cache:
        key: node-{{ .Environment.NODE_VERSION }}-cache-{{ checksum "./yarn.lock" }}
        paths:
          - ~/.yarn-cache
          - ./node_modules
    - persist_to_workspace:
        root: ~/repo
        paths:
          - ./

jobs:
  install_lint_test-node10:
    docker:
      - image: circleci/node:10
    <<: [*defaults, *install_lint_test]
  install_lint_test-node12:
    docker:
      - image: circleci/node:12
    <<: [*defaults, *install_lint_test]
  deploy:
    docker:
      - image: circleci/node:12
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys:
          fingerprints:
            - '8b:f7:d2:02:79:da:61:b8:c1:23:11:06:87:84:58:eb'
      - run:
          name: Configure git
          command: |
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts

            git config --global user.email "xeroxinteractive-circleci@xerox.com"
            git config --global user.name "CircleCI"
      - run:
          name: Deploy package to npm
          command: yarn deploy

workflows:
  version: 2
  install_lint_deploy:
    jobs:
      - install_lint_test-node10:
          context: node10
      - install_lint_test-node12:
          context: node12
      - deploy:
          context: npm
          requires:
            - install_lint_test-node10
            - install_lint_test-node12
          filters:
            branches:
              only:
                - master
